version: "3.9"

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - feedfordb
            - redis

    feedfordb:
        image: postgres:13
        environment:
            POSTGRES_DB: feedfordb
            POSTGRES_USER: feedfordbuser
            POSTGRES_PASSWORD: feedfordbpassword
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    redis:
        image: redis:latest

    celery:
        build: .
        command: celery -A feedfor worker --loglevel=info
        volumes:
            - .:/code
        depends_on:
            - web
            - redis

volumes:
    postgres_data:
